In [1]:
"""
@autor: Yuri Idalgo de Matos da Silva
criado em: 19/06/2026
descrição: Script para realizar a traco dos nomes das colunas que são necessárias para fazer a SMC.
"""

'\n@autor: Yuri Idalgo de Matos da Silva\ncriado em: 19/06/2026\ndescrição: Script para realizar a traco dos nomes das colunas que são necessárias para fazer a SMC.\n'

In [2]:
# Importando as bibliotecas necessárias
import pandas as pd
import numpy as np
import os

In [3]:
# Leitura de dados

data_dir = r"C:\Users\x432601\Downloads\SIMULACAO_MONTE_CARLO\data_testes\data"
file01 = r"calculo-emissao-poluentes-diario_2026-01-01_silver.csv"

df_consume_table = pd.read_csv(os.path.join(data_dir, file01), sep = ",")

In [4]:
df_consume_table.head()

,codigo_onibus,distancia_percorrida,segundos_deslocamento,tecnologia,fase_conama,fator_consumo_l,fator_consumo_kg,consumo_l,consumo_kg,emissao_co2,emissao_mp,emissao_nox
0,3106,2503.785899,11618.0,Básico,P5,0.53,0.445,1.327007,1.114185,3.544434,0.043230,0.023378
1,3117,113066.908983,31506.0,Articulado (18m),P5,0.80,0.672,90.453527,75.980963,241.601371,2.948061,1.594233
2,3211,7636.302437,392.0,Padron,P7,0.63,0.529,4.810871,4.039604,12.849835,0.002222,0.265604
3,5120,33113.026071,6517.0,Midiônibus,P5,0.47,0.395,15.563122,13.079645,41.569100,0.507490,0.274437
4,7302,33360.392767,39040.0,Articulado (18m),P5,0.80,0.672,26.688314,22.418184,71.284487,0.869826,0.470378

In [5]:
df_consume_table.describe()

,codigo_onibus,distancia_percorrida,segundos_deslocamento,fator_consumo_l,fator_consumo_kg,consumo_l,consumo_kg,emissao_co2,emissao_mp,emissao_nox
count,6434.000000,6.434000e+03,6434.000000,6434.000000,6434.000000,6434.000000,6434.000000,6434.000000,6434.000000,6434.000000
mean,49219.514144,1.626982e+05,54553.802300,0.649866,0.545862,105.499912,88.615589,281.790266,1.116227,2.615777
std,22171.678243,1.262838e+05,26035.275001,0.195045,0.163831,94.485486,79.364769,252.370732,2.236597,3.744427
min,3106.000000,0.000000e+00,0.000000,0.350000,0.294000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31612.250000,7.931882e+04,37452.500000,0.470000,0.395000,44.289182,37.213526,118.296405,0.002405,0.099921
50%,48755.500000,1.593754e+05,57960.500000,0.630000,0.529000,93.291899,78.332784,249.182662,0.035720,1.094868
75%,68054.500000,2.225180e+05,82406.250000,0.850000,0.714000,147.808516,124.159153,394.796546,1.196746,3.724052
max,90999.000000,4.353018e+06,134397.000000,0.900000,0.756000,3700.064876,3108.054496,9882.873284,26.082750,44.352525

In [6]:
# Renomeando e trocando dimensão das colunas de emissões para toneladas (t)
df_consume_table = df_consume_table.rename(columns = {'emissao_co2': 'emissao_co2(t)', 'emissao_mp' : 'emissao_mp(t)', 'emissao_nox':'emissao_nox(t)' })
df_consume_table['emissao_co2(t)'] = df_consume_table['emissao_co2(t)'] / 1000 # Convertendo de kg para toneladas

In [7]:
# Salvando o arquivo corrigido
output_file = r"calculo-emissao-poluentes-diario_2026-01-01_silver_corrigido.csv"
df_consume_table.to_csv(os.path.join(data_dir, output_file), index = False)

In [8]:
print(df_consume_table.columns.to_list())

['codigo_onibus', 'distancia_percorrida', 'segundos_deslocamento', 'tecnologia', 'fase_conama', 'fator_consumo_l', 'fator_consumo_kg', 'consumo_l', 'consumo_kg', 'emissao_co2(t)', 'emissao_mp(t)', 'emissao_nox(t)']